<?php
/**
 * PHP functions for MODULE
 */

function du_banners_theme($existing, $type, $theme, $path) {
  return [
    'alert' => [
      'variables' => ['content' => NULL],
      'template' => 'alert',
      'path' => $path . '/templates/misc',
    ],
    'alert_urgent_page' => [
      'variables' => ['content' => NULL],
      'template' => 'alert-urgent-page',
      'path' => $path . '/templates/misc',
    ],
    'node__alert' => [
      'render element' => 'elements',
      'base hook' => 'node',
      'template' => 'node--alert',
      'path' => $path . '/templates/node',
    ],
  ];
}

function du_banners_theme_suggestions_node_alter(array &$suggestions, array $variables) {
  $node = $variables['elements']['#node'];
  if ($node instanceof \Drupal\node\NodeInterface && $node->bundle() === 'alert') {
    $suggestions[] = 'node__alert';
  }
}
