name: e2e

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      upstream_ref:
        description: 'Optional ref (branch/tag/SHA) of drupal-composer-managed to use'
        required: false
        default: ''

# Avoid overlapping runs per branch
concurrency:
  group: e2e-${{ github.ref }}
  cancel-in-progress: true

jobs:
  playwright:
    runs-on: ubuntu-22.04
    env:
      PLAYWRIGHT_BASE_URL: https://drupal-composer-managed.ddev.site

    steps:
      - name: Checkout module
        uses: actions/checkout@v4
        with:
          path: module

      - name: Setup DDEV
        uses: ddev/github-action-setup-ddev@v1
        with:
          autostart: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Checkout Drupal upstream
        uses: actions/checkout@v4
        with:
          repository: DU-University-Relations/drupal-composer-managed
          path: upstream
          token: ${{ secrets.GITHUB_TOKEN }}
          # Testing with a specific ref from PR.
          ref: 'w1775318155'
          # ref: ${{ github.event.inputs.upstream_ref || '' }}

      - name: Start DDEV in upstream directory
        working-directory: upstream
        run: ddev start

#      - name: Debug listings
#        run: |
#          pwd
#          ls -al .
#          ls -al upstream/web/modules/custom

      - name: Bootstrap upstream with module and tests
        working-directory: module
        run: bash scripts/bootstrap-ci.sh

      - name: Install Playwright browsers (CI)
        working-directory: upstream
        run: npx playwright install --with-deps

      - name: Run Playwright tests for banners
        working-directory: upstream
        run: npx playwright test --grep @banners

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: upstream/tests/playwright-report
          if-no-files-found: ignore
